import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./components/footer";
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'], // regular, medium, semibold
  variable: '--font-poppins',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
${poppins.variable}
antialiased`}
      >
        {children}
		<Footer />
      </body>
    </html>
  );
}
